[tools]
node = "22"
"ubi:ajeetdsouza/zoxide" = "latest"
"ubi:pnpm/pnpm" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:neovim/neovim" = "latest"
"ubi:jj-vcs/jj" = "latest"
"ubi:dandavison/delta" = "latest"
"aqua:helix-editor/helix" = "latest"
"aqua:chmln/sd" = "latest"
"core:bun" = "latest"

[settings]
idiomatic_version_file_enable_tools = []

[env]
_.path = ["~/.cache/.bun/bin"]
